# permissions for end users to edit sloopcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sloopcontroller-editor-role
rules:
- apiGroups:
  - controller.sloop.io
  resources:
  - sloopcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.sloop.io
  resources:
  - sloopcontrollers/status
  verbs:
  - get
